<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ELHI772V" failures="3" tests="14" name="PetTest" time="19.764" errors="0" timestamp="2025-02-27T16:42:41 IST">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="2.548"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.168"/>
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="2.345"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.212">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testDeleteUserByName(UserTests2.java:100)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.StoreTest" name="testGetUserByName" time="1.149"/>
  <testcase classname="api.test.StoreTest" name="testPostUser" time="1.158"/>
  <testcase classname="api.test.StoreTest" name="testGetUserByOrderID" time="1.167"/>
  <testcase classname="api.test.StoreTest" name="deleteOrderById" time="1.183">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.StoreTest.deleteOrderById(StoreTest.java:92)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- deleteOrderById -->
  <testcase classname="api.test.PetsTest" name="testPostPets" time="1.216"/>
  <testcase classname="api.test.PetsTest" name="testPostPetsUpload" time="1.223"/>
  <testcase classname="api.test.PetsTest" name="testputPets" time="1.15"/>
  <testcase classname="api.test.PetsTest" name="getpetstatus" time="1.133"/>
  <testcase classname="api.test.PetsTest" name="testGetpetByPetID" time="1.142">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.PetsTest.testGetpetByPetID(PetsTest.java:118)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetpetByPetID -->
  <testcase classname="api.test.PetsTest" name="deleteOrderById" time="1.184"/>
</testsuite> <!-- PetTest -->
